"""adds user profile

Revision ID: 937375697ded
Revises: 94ad17d8bf43
Create Date: 2018-09-05 07:52:51.517745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937375697ded'
down_revision = '94ad17d8bf43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
